version: '3.7'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "swaggerimple"
      MYSQL_ROOT_PASSWORD: "Vaish@099"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "SwaggerImplementation"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/swaggerimple"  # Connect to the mysql container by service name
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Vaish@099"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge
